### ISSUE TITLE
Exception when the player exits the server

### ISSUE THREAD

**Issue by funpin** [vanutp/tgbridge#11]
Hi! I installed your plugin and I'm very happy! However, one caveat arises: when a player leaves the server, the message does not arrive in the tg channel, because an exception occurs on the server:

`[08:56:24 WARN]: Exception in thread "DefaultDispatcher-worker-3" java.lang.Exception: Telegram exception: {"ok":false,"error_code":400,"description":"Bad Request: can't parse entities: Unexpected end tag at byte offset 47"}
[08:56:24 WARN]:        at tgbridge-0.4.4-paper.jar//dev.vanutp.tgbridge.common.TelegramBot.call(TelegramBot.kt:308)
[08:56:24 WARN]:        at tgbridge-0.4.4-paper.jar//dev.vanutp.tgbridge.common.TelegramBot.access$call(TelegramBot.kt:203)
[08:56:24 WARN]:        at tgbridge-0.4.4-paper.jar//dev.vanutp.tgbridge.common.TelegramBot$call$1.invokeSuspend(TelegramBot.kt)
[08:56:24 WARN]:        at tgbridge-0.4.4-paper.jar//kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[08:56:24 WARN]:        at tgbridge-0.4.4-paper.jar//kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
[08:56:24 WARN]:        at tgbridge-0.4.4-paper.jar//kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
[08:56:24 WARN]:        at tgbridge-0.4.4-paper.jar//kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
[08:56:24 WARN]:        at tgbridge-0.4.4-paper.jar//kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
[08:56:24 WARN]:        at tgbridge-0.4.4-paper.jar//kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
[08:56:24 WARN]:        at tgbridge-0.4.4-paper.jar//kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
[08:56:24 WARN]:        at tgbridge-0.4.4-paper.jar//kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
[08:56:24 WARN]:        Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@3334a77, Dispatchers.IO] `

The core on the sever: paper-1.21-130

Can you tell me what the error might be? 
Thank you in advance!

**Comment by funpin** [comment]
На сервере стоит несколько плагинов, в том числе - которые меняют сообщения чата о входе/выходе игрока, но я не уверен, что их работа как-то сказывается на работе плагина, поскольку сообщение о входе приходит
![IMG_4971](https://github.com/user-attachments/assets/5f8b1476-da73-48f6-adc6-679c4b090caf)

**Comment by vanutp** [comment]
Покажите, пожалуйста, `lang.yml`

**Comment by funpin** [comment]
`# Translations to other languages can be downloaded from https://github.com/vanutp/tgbridge
telegram:
  serverStarted: "✅ <b>Сервер запустился!</b>"
  serverStopped: "❌ <b>Сервер выключился.</b>"
  playerJoined: "🟢 <b>{username}</b> зашёл на сервер"
  playerLeft: "🔴 <b>{username}</b> вышел с сервера</b>"
  playerDied: "☠️ <b>{deathMessage}</b>"
  chatMessage: "<b>{username} >></b> {text}"
  advancements:
    regular: "😼 <b>{username} has made the advancement {title}</b>\n\n<i>{description}</i>"
    goal: "🎯 <b>{username} has reached the goal {title}</b>\n\n<i>{description}</i>"
    challenge: "🏅 <b>{username} has completed the challenge {title}</b>\n\n<i>{description}</i>"
  playerList: "📝 <b>{count} игроков онлайн:</b> {usernames}"
  playerListZeroOnline: "📝 <b>Никого нет на серере :( </b>"
minecraft:
  messageMeta:
    reply: "[R {sender}: {text}]"
    replyToMinecraft: "[R {text}]"
    forward: "[F {from}]"
    gif: "[GIF]"
    document: "[Document]"
    photo: "[Photo]"
    audio: "[Audio]"
    sticker: "[Sticker]"
    video: "[Video]"
    videoMessage: "[Video message]"
    voiceMessage: "[Voice message]"
    poll: "[Poll: {title}]"
`

**Comment by funpin** [comment]
# Translations to other languages can be downloaded from https://github.com/vanutp/tgbridge
telegram:
  serverStarted: "✅ <b>Сервер запустился!</b>"
  serverStopped: "❌ <b>Сервер выключился.</b>"
  playerJoined: "🟢 <b>{username}</b> зашёл на сервер"
  playerLeft: "🔴 <b>{username}</b> вышел с сервера</b>"
  playerDied: "☠️ <b>{deathMessage}</b>"
  chatMessage: "<b>{username} >></b> {text}"
  advancements:
    regular: "😼 <b>{username} has made the advancement {title}</b>\n\n<i>{description}</i>"
    goal: "🎯 <b>{username} has reached the goal {title}</b>\n\n<i>{description}</i>"
    challenge: "🏅 <b>{username} has completed the challenge {title}</b>\n\n<i>{description}</i>"
  playerList: "📝 <b>{count} игроков онлайн:</b> {usernames}"
  playerListZeroOnline: "📝 <b>Никого нет на серере :( </b>"
minecraft:
  messageMeta:
    reply: "[R {sender}: {text}]"
    replyToMinecraft: "[R {text}]"
    forward: "[F {from}]"
    gif: "[GIF]"
    document: "[Document]"
    photo: "[Photo]"
    audio: "[Audio]"
    sticker: "[Sticker]"
    video: "[Video]"
    videoMessage: "[Video message]"
    voiceMessage: "[Voice message]"
    poll: "[Poll: {title}]"

**Comment by funpin** [comment]
[lang.txt](https://github.com/user-attachments/files/16647569/lang.txt)

**Comment by vanutp** [comment]
В `playerLeft` лишний `</b>` в конце)

**Comment by funpin** [comment]
> В `playerLeft` лишний `</b>` в конце)

О боже мой, проглядел.
Прошу прощения, спасибо)
