### ISSUE TITLE
Error on empty command /tgbridge

### ISSUE THREAD

**Issue by KosyakMakc** [vanutp/tgbridge#23]
in game just typing "/tgbridge" I got error:
```
org.bukkit.command.CommandException: Unhandled exception executing command 'tgbridge' in plugin tgbridge v0.4.5
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91) ~[folia-1.21.1.jar:1.21.1-DEV-88e0907]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.3.10.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[folia-1.21.1.jar:1.21.1-DEV-88e0907]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[folia-1.21.1.jar:1.21.1-DEV-88e0907]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[folia-1.21.1.jar:1.21.1-DEV-88e0907]
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[folia-1.21.1.jar:1.21.1-DEV-88e0907]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[folia-1.21.1.jar:1.21.1-DEV-88e0907]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:443) ~[folia-1.21.1.jar:1.21.1-DEV-88e0907]
        at net.minecraft.commands.Commands.performCommand(Commands.java:350) ~[folia-1.21.1.jar:1.21.1-DEV-88e0907]
        at net.minecraft.commands.Commands.performCommand(Commands.java:337) ~[folia-1.21.1.jar:1.21.1-DEV-88e0907]
        at net.minecraft.commands.Commands.performCommand(Commands.java:332) ~[folia-1.21.1.jar:1.21.1-DEV-88e0907]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2199) ~[folia-1.21.1.jar:1.21.1-DEV-88e0907]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2173) ~[folia-1.21.1.jar:1.21.1-DEV-88e0907]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$tryHandleChat$17(ServerGamePacketListenerImpl.java:2337) ~[folia-1.21.1.jar:1.21.1-DEV-88e0907]
        at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173) ~[folia-1.21.1.jar:1.21.1-DEV-88e0907]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1711) ~[folia-1.21.1.jar:1.21.1-DEV-88e0907]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407) ~[folia-1.21.1.jar:1.21.1-DEV-88e0907]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:409) ~[folia-1.21.1.jar:1.21.1-DEV-88e0907]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:540) ~[folia-1.21.1.jar:1.21.1-DEV-88e0907]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at tgbridge-paper-0.4.5-dev-all.jar/dev.vanutp.tgbridge.paper.PaperPlatform.registerCommand$lambda$1(PaperPlatform.kt:78) ~[tgbridge-paper-0.4.5-dev-all.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        ... 20 more
```

**Comment by sibmaks** [comment]
@vanutp Looks like it was fixed in this commit https://github.com/vanutp/tgbridge/commit/fa54da68e2ee41b878518eaa88aa679d2de6928b
This code were refactored https://github.com/vanutp/tgbridge/commit/fa54da68e2ee41b878518eaa88aa679d2de6928b#diff-da4917b1c5a55cfc134d16fdd633fa46e40a15ce1f9a83944ec3bbfc06153d5fL12-L103
