### ISSUE TITLE
Crash on launch with MiniMOTD mod installed

### ISSUE THREAD

**Issue by purrloftruth** [vanutp/tgbridge#34]
NeoForge 21.1.72, MiniMOTD 2.1.3, tgbridge 0.4.6.

Workaround: disable MiniMOTD until the bug can be fixed in tgbridge.

A similarly-presenting bug was recently fixed in Spark in 1.10.110 in this commit, if this information is helpful: https://github.com/lucko/spark/commit/6effd0d018db25c53c042a88d50e5b43dfca56bd

Crash exception:
`Exception in thread "main" java.lang.module.ResolutionException: Modules net.kyori.adventure.text.serializer.gson and tgbridge export package net.kyori.adventure.text.serializer.gson.impl to module clumps
        at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:900)
        at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:814)
        at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:735)
        at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
        at java.base/java.lang.module.Configuration.<init>(Configuration.java:139)
        at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:493)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:54)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:101)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210)
        at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69)`

**Comment by vanutp** [comment]
Thanks, fixed in 0.4.7
